package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Alerta generated by hbm2java
 */
public class Alerta  implements java.io.Serializable {


     private Integer aleid;
     private String aletipo;
     private String alecolor;
     private Set configuracions = new HashSet(0);
     private Set calendarioreporteTieneAlertas = new HashSet(0);
     private Set mensajes = new HashSet(0);

    public Alerta() {
    }

	
    public Alerta(String aletipo) {
        this.aletipo = aletipo;
    }
    public Alerta(String aletipo, String alecolor, Set configuracions, Set calendarioreporteTieneAlertas, Set mensajes) {
       this.aletipo = aletipo;
       this.alecolor = alecolor;
       this.configuracions = configuracions;
       this.calendarioreporteTieneAlertas = calendarioreporteTieneAlertas;
       this.mensajes = mensajes;
    }
   
    public Integer getAleid() {
        return this.aleid;
    }
    
    public void setAleid(Integer aleid) {
        this.aleid = aleid;
    }
    public String getAletipo() {
        return this.aletipo;
    }
    
    public void setAletipo(String aletipo) {
        this.aletipo = aletipo;
    }
    public String getAlecolor() {
        return this.alecolor;
    }
    
    public void setAlecolor(String alecolor) {
        this.alecolor = alecolor;
    }
    public Set getConfiguracions() {
        return this.configuracions;
    }
    
    public void setConfiguracions(Set configuracions) {
        this.configuracions = configuracions;
    }
    public Set getCalendarioreporteTieneAlertas() {
        return this.calendarioreporteTieneAlertas;
    }
    
    public void setCalendarioreporteTieneAlertas(Set calendarioreporteTieneAlertas) {
        this.calendarioreporteTieneAlertas = calendarioreporteTieneAlertas;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set mensajes) {
        this.mensajes = mensajes;
    }




}


