package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Areaconocimiento generated by hbm2java
 */
public class Areaconocimiento  implements java.io.Serializable {


     private Integer acoid;
     private Planestudio planestudio;
     private int acoclave;
     private String aconombre;
     private Set profesors = new HashSet(0);
     private Set unidadaprendizajes = new HashSet(0);

    public Areaconocimiento() {
    }

	
    public Areaconocimiento(int acoclave) {
        this.acoclave = acoclave;
    }
    public Areaconocimiento(Planestudio planestudio, int acoclave, String aconombre, Set profesors, Set unidadaprendizajes) {
       this.planestudio = planestudio;
       this.acoclave = acoclave;
       this.aconombre = aconombre;
       this.profesors = profesors;
       this.unidadaprendizajes = unidadaprendizajes;
    }
   
    public Integer getAcoid() {
        return this.acoid;
    }
    
    public void setAcoid(Integer acoid) {
        this.acoid = acoid;
    }
    public Planestudio getPlanestudio() {
        return this.planestudio;
    }
    
    public void setPlanestudio(Planestudio planestudio) {
        this.planestudio = planestudio;
    }
    public int getAcoclave() {
        return this.acoclave;
    }
    
    public void setAcoclave(int acoclave) {
        this.acoclave = acoclave;
    }
    public String getAconombre() {
        return this.aconombre;
    }
    
    public void setAconombre(String aconombre) {
        this.aconombre = aconombre;
    }
    public Set getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set profesors) {
        this.profesors = profesors;
    }
    public Set getUnidadaprendizajes() {
        return this.unidadaprendizajes;
    }
    
    public void setUnidadaprendizajes(Set unidadaprendizajes) {
        this.unidadaprendizajes = unidadaprendizajes;
    }




}


