package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Areaadministrativa generated by hbm2java
 */
public class Areaadministrativa  implements java.io.Serializable {


     private Integer aadid;
     private Programaeducativo programaeducativo;
     private String aadnombre;
     private Set coordinadorareaadministrativas = new HashSet(0);

    public Areaadministrativa() {
    }

	
    public Areaadministrativa(Programaeducativo programaeducativo, String aadnombre) {
        this.programaeducativo = programaeducativo;
        this.aadnombre = aadnombre;
    }
    public Areaadministrativa(Programaeducativo programaeducativo, String aadnombre, Set coordinadorareaadministrativas) {
       this.programaeducativo = programaeducativo;
       this.aadnombre = aadnombre;
       this.coordinadorareaadministrativas = coordinadorareaadministrativas;
    }
   
    public Integer getAadid() {
        return this.aadid;
    }
    
    public void setAadid(Integer aadid) {
        this.aadid = aadid;
    }
    public Programaeducativo getProgramaeducativo() {
        return this.programaeducativo;
    }
    
    public void setProgramaeducativo(Programaeducativo programaeducativo) {
        this.programaeducativo = programaeducativo;
    }
    public String getAadnombre() {
        return this.aadnombre;
    }
    
    public void setAadnombre(String aadnombre) {
        this.aadnombre = aadnombre;
    }
    public Set getCoordinadorareaadministrativas() {
        return this.coordinadorareaadministrativas;
    }
    
    public void setCoordinadorareaadministrativas(Set coordinadorareaadministrativas) {
        this.coordinadorareaadministrativas = coordinadorareaadministrativas;
    }




}


