package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0



/**
 * CalendarioreporteTieneAlertaId generated by hbm2java
 */
public class CalendarioreporteTieneAlertaId  implements java.io.Serializable {


     private int calendarioReporteCreid;
     private int alertaAleid;

    public CalendarioreporteTieneAlertaId() {
    }

    public CalendarioreporteTieneAlertaId(int calendarioReporteCreid, int alertaAleid) {
       this.calendarioReporteCreid = calendarioReporteCreid;
       this.alertaAleid = alertaAleid;
    }
   
    public int getCalendarioReporteCreid() {
        return this.calendarioReporteCreid;
    }
    
    public void setCalendarioReporteCreid(int calendarioReporteCreid) {
        this.calendarioReporteCreid = calendarioReporteCreid;
    }
    public int getAlertaAleid() {
        return this.alertaAleid;
    }
    
    public void setAlertaAleid(int alertaAleid) {
        this.alertaAleid = alertaAleid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CalendarioreporteTieneAlertaId) ) return false;
		 CalendarioreporteTieneAlertaId castOther = ( CalendarioreporteTieneAlertaId ) other; 
         
		 return (this.getCalendarioReporteCreid()==castOther.getCalendarioReporteCreid())
 && (this.getAlertaAleid()==castOther.getAlertaAleid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCalendarioReporteCreid();
         result = 37 * result + this.getAlertaAleid();
         return result;
   }   


}


