package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0



/**
 * CalendarioreporteTieneAlerta generated by hbm2java
 */
public class CalendarioreporteTieneAlerta  implements java.io.Serializable {


     private CalendarioreporteTieneAlertaId id;
     private Calendarioreporte calendarioreporte;
     private Alerta alerta;
     private int caldias;
     private Integer calnumeroReporte;

    public CalendarioreporteTieneAlerta() {
    }

	
    public CalendarioreporteTieneAlerta(CalendarioreporteTieneAlertaId id, Calendarioreporte calendarioreporte, Alerta alerta, int caldias) {
        this.id = id;
        this.calendarioreporte = calendarioreporte;
        this.alerta = alerta;
        this.caldias = caldias;
    }
    public CalendarioreporteTieneAlerta(CalendarioreporteTieneAlertaId id, Calendarioreporte calendarioreporte, Alerta alerta, int caldias, Integer calnumeroReporte) {
       this.id = id;
       this.calendarioreporte = calendarioreporte;
       this.alerta = alerta;
       this.caldias = caldias;
       this.calnumeroReporte = calnumeroReporte;
    }
   
    public CalendarioreporteTieneAlertaId getId() {
        return this.id;
    }
    
    public void setId(CalendarioreporteTieneAlertaId id) {
        this.id = id;
    }
    public Calendarioreporte getCalendarioreporte() {
        return this.calendarioreporte;
    }
    
    public void setCalendarioreporte(Calendarioreporte calendarioreporte) {
        this.calendarioreporte = calendarioreporte;
    }
    public Alerta getAlerta() {
        return this.alerta;
    }
    
    public void setAlerta(Alerta alerta) {
        this.alerta = alerta;
    }
    public int getCaldias() {
        return this.caldias;
    }
    
    public void setCaldias(int caldias) {
        this.caldias = caldias;
    }
    public Integer getCalnumeroReporte() {
        return this.calnumeroReporte;
    }
    
    public void setCalnumeroReporte(Integer calnumeroReporte) {
        this.calnumeroReporte = calnumeroReporte;
    }




}


