package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Campus generated by hbm2java
 */
public class Campus  implements java.io.Serializable {


     private Integer camid;
     private String camnombre;
     private Set unidadacademicas = new HashSet(0);

    public Campus() {
    }

	
    public Campus(String camnombre) {
        this.camnombre = camnombre;
    }
    public Campus(String camnombre, Set unidadacademicas) {
       this.camnombre = camnombre;
       this.unidadacademicas = unidadacademicas;
    }
   
    public Integer getCamid() {
        return this.camid;
    }
    
    public void setCamid(Integer camid) {
        this.camid = camid;
    }
    public String getCamnombre() {
        return this.camnombre;
    }
    
    public void setCamnombre(String camnombre) {
        this.camnombre = camnombre;
    }
    public Set getUnidadacademicas() {
        return this.unidadacademicas;
    }
    
    public void setUnidadacademicas(Set unidadacademicas) {
        this.unidadacademicas = unidadacademicas;
    }




}


