package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cicloescolar generated by hbm2java
 */
public class Cicloescolar  implements java.io.Serializable {


     private Integer cesid;
     private String cescicloEscolar;
     private Set unidadaprendizajes = new HashSet(0);
     private Set configuracions = new HashSet(0);

    public Cicloescolar() {
    }

    public Cicloescolar(String cescicloEscolar, Set unidadaprendizajes, Set configuracions) {
       this.cescicloEscolar = cescicloEscolar;
       this.unidadaprendizajes = unidadaprendizajes;
       this.configuracions = configuracions;
    }
   
    public Integer getCesid() {
        return this.cesid;
    }
    
    public void setCesid(Integer cesid) {
        this.cesid = cesid;
    }
    public String getCescicloEscolar() {
        return this.cescicloEscolar;
    }
    
    public void setCescicloEscolar(String cescicloEscolar) {
        this.cescicloEscolar = cescicloEscolar;
    }
    public Set getUnidadaprendizajes() {
        return this.unidadaprendizajes;
    }
    
    public void setUnidadaprendizajes(Set unidadaprendizajes) {
        this.unidadaprendizajes = unidadaprendizajes;
    }
    public Set getConfiguracions() {
        return this.configuracions;
    }
    
    public void setConfiguracions(Set configuracions) {
        this.configuracions = configuracions;
    }




}


