package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0



/**
 * Coordinadorareaadministrativa generated by hbm2java
 */
public class Coordinadorareaadministrativa  implements java.io.Serializable {


     private CoordinadorareaadministrativaId id;
     private Unidadaprendizaje unidadaprendizaje;
     private Profesor profesor;
     private Areaadministrativa areaadministrativa;

    public Coordinadorareaadministrativa() {
    }

    public Coordinadorareaadministrativa(CoordinadorareaadministrativaId id, Unidadaprendizaje unidadaprendizaje, Profesor profesor, Areaadministrativa areaadministrativa) {
       this.id = id;
       this.unidadaprendizaje = unidadaprendizaje;
       this.profesor = profesor;
       this.areaadministrativa = areaadministrativa;
    }
   
    public CoordinadorareaadministrativaId getId() {
        return this.id;
    }
    
    public void setId(CoordinadorareaadministrativaId id) {
        this.id = id;
    }
    public Unidadaprendizaje getUnidadaprendizaje() {
        return this.unidadaprendizaje;
    }
    
    public void setUnidadaprendizaje(Unidadaprendizaje unidadaprendizaje) {
        this.unidadaprendizaje = unidadaprendizaje;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Areaadministrativa getAreaadministrativa() {
        return this.areaadministrativa;
    }
    
    public void setAreaadministrativa(Areaadministrativa areaadministrativa) {
        this.areaadministrativa = areaadministrativa;
    }




}


