package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0



/**
 * CoordinadorareaadministrativaId generated by hbm2java
 */
public class CoordinadorareaadministrativaId  implements java.io.Serializable {


     private int profesorProid;
     private int unidadAprendizajeUapid;

    public CoordinadorareaadministrativaId() {
    }

    public CoordinadorareaadministrativaId(int profesorProid, int unidadAprendizajeUapid) {
       this.profesorProid = profesorProid;
       this.unidadAprendizajeUapid = unidadAprendizajeUapid;
    }
   
    public int getProfesorProid() {
        return this.profesorProid;
    }
    
    public void setProfesorProid(int profesorProid) {
        this.profesorProid = profesorProid;
    }
    public int getUnidadAprendizajeUapid() {
        return this.unidadAprendizajeUapid;
    }
    
    public void setUnidadAprendizajeUapid(int unidadAprendizajeUapid) {
        this.unidadAprendizajeUapid = unidadAprendizajeUapid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CoordinadorareaadministrativaId) ) return false;
		 CoordinadorareaadministrativaId castOther = ( CoordinadorareaadministrativaId ) other; 
         
		 return (this.getProfesorProid()==castOther.getProfesorProid())
 && (this.getUnidadAprendizajeUapid()==castOther.getUnidadAprendizajeUapid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProfesorProid();
         result = 37 * result + this.getUnidadAprendizajeUapid();
         return result;
   }   


}


