package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0



/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private Integer menid;
     private Alerta alerta;
     private String menmensaje;

    public Mensaje() {
    }

    public Mensaje(Alerta alerta, String menmensaje) {
       this.alerta = alerta;
       this.menmensaje = menmensaje;
    }
   
    public Integer getMenid() {
        return this.menid;
    }
    
    public void setMenid(Integer menid) {
        this.menid = menid;
    }
    public Alerta getAlerta() {
        return this.alerta;
    }
    
    public void setAlerta(Alerta alerta) {
        this.alerta = alerta;
    }
    public String getMenmensaje() {
        return this.menmensaje;
    }
    
    public void setMenmensaje(String menmensaje) {
        this.menmensaje = menmensaje;
    }




}


