package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private Integer perid;
     private String pertipo;
     private int pervalor;
     private Set rolHasPermisos = new HashSet(0);

    public Permiso() {
    }

	
    public Permiso(String pertipo, int pervalor) {
        this.pertipo = pertipo;
        this.pervalor = pervalor;
    }
    public Permiso(String pertipo, int pervalor, Set rolHasPermisos) {
       this.pertipo = pertipo;
       this.pervalor = pervalor;
       this.rolHasPermisos = rolHasPermisos;
    }
   
    public Integer getPerid() {
        return this.perid;
    }
    
    public void setPerid(Integer perid) {
        this.perid = perid;
    }
    public String getPertipo() {
        return this.pertipo;
    }
    
    public void setPertipo(String pertipo) {
        this.pertipo = pertipo;
    }
    public int getPervalor() {
        return this.pervalor;
    }
    
    public void setPervalor(int pervalor) {
        this.pervalor = pervalor;
    }
    public Set getRolHasPermisos() {
        return this.rolHasPermisos;
    }
    
    public void setRolHasPermisos(Set rolHasPermisos) {
        this.rolHasPermisos = rolHasPermisos;
    }




}


