package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Planestudio generated by hbm2java
 */
public class Planestudio  implements java.io.Serializable {


     private Integer pesid;
     private Programaeducativo programaeducativo;
     private String pesvigenciaPlan;
     private int pescreditosObligatorios;
     private int pescreditosOptativos;
     private int pestotalCreditos;
     private Set areaconocimientos = new HashSet(0);
     private Set grupos = new HashSet(0);

    public Planestudio() {
    }

	
    public Planestudio(String pesvigenciaPlan, int pescreditosObligatorios, int pescreditosOptativos, int pestotalCreditos) {
        this.pesvigenciaPlan = pesvigenciaPlan;
        this.pescreditosObligatorios = pescreditosObligatorios;
        this.pescreditosOptativos = pescreditosOptativos;
        this.pestotalCreditos = pestotalCreditos;
    }
    public Planestudio(Programaeducativo programaeducativo, String pesvigenciaPlan, int pescreditosObligatorios, int pescreditosOptativos, int pestotalCreditos, Set areaconocimientos, Set grupos) {
       this.programaeducativo = programaeducativo;
       this.pesvigenciaPlan = pesvigenciaPlan;
       this.pescreditosObligatorios = pescreditosObligatorios;
       this.pescreditosOptativos = pescreditosOptativos;
       this.pestotalCreditos = pestotalCreditos;
       this.areaconocimientos = areaconocimientos;
       this.grupos = grupos;
    }
   
    public Integer getPesid() {
        return this.pesid;
    }
    
    public void setPesid(Integer pesid) {
        this.pesid = pesid;
    }
    public Programaeducativo getProgramaeducativo() {
        return this.programaeducativo;
    }
    
    public void setProgramaeducativo(Programaeducativo programaeducativo) {
        this.programaeducativo = programaeducativo;
    }
    public String getPesvigenciaPlan() {
        return this.pesvigenciaPlan;
    }
    
    public void setPesvigenciaPlan(String pesvigenciaPlan) {
        this.pesvigenciaPlan = pesvigenciaPlan;
    }
    public int getPescreditosObligatorios() {
        return this.pescreditosObligatorios;
    }
    
    public void setPescreditosObligatorios(int pescreditosObligatorios) {
        this.pescreditosObligatorios = pescreditosObligatorios;
    }
    public int getPescreditosOptativos() {
        return this.pescreditosOptativos;
    }
    
    public void setPescreditosOptativos(int pescreditosOptativos) {
        this.pescreditosOptativos = pescreditosOptativos;
    }
    public int getPestotalCreditos() {
        return this.pestotalCreditos;
    }
    
    public void setPestotalCreditos(int pestotalCreditos) {
        this.pestotalCreditos = pestotalCreditos;
    }
    public Set getAreaconocimientos() {
        return this.areaconocimientos;
    }
    
    public void setAreaconocimientos(Set areaconocimientos) {
        this.areaconocimientos = areaconocimientos;
    }
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }




}


