package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0



/**
 * Practicasclinica generated by hbm2java
 */
public class Practicasclinica  implements java.io.Serializable {


     private int prcid;
     private Unidadaprendizaje unidadaprendizaje;
     private Integer prcnumero;
     private String prcnombre;
     private Float prcvalorPorcentaje;
     private Integer prchoras;

    public Practicasclinica() {
    }

	
    public Practicasclinica(int prcid, Unidadaprendizaje unidadaprendizaje) {
        this.prcid = prcid;
        this.unidadaprendizaje = unidadaprendizaje;
    }
    public Practicasclinica(int prcid, Unidadaprendizaje unidadaprendizaje, Integer prcnumero, String prcnombre, Float prcvalorPorcentaje, Integer prchoras) {
       this.prcid = prcid;
       this.unidadaprendizaje = unidadaprendizaje;
       this.prcnumero = prcnumero;
       this.prcnombre = prcnombre;
       this.prcvalorPorcentaje = prcvalorPorcentaje;
       this.prchoras = prchoras;
    }
   
    public int getPrcid() {
        return this.prcid;
    }
    
    public void setPrcid(int prcid) {
        this.prcid = prcid;
    }
    public Unidadaprendizaje getUnidadaprendizaje() {
        return this.unidadaprendizaje;
    }
    
    public void setUnidadaprendizaje(Unidadaprendizaje unidadaprendizaje) {
        this.unidadaprendizaje = unidadaprendizaje;
    }
    public Integer getPrcnumero() {
        return this.prcnumero;
    }
    
    public void setPrcnumero(Integer prcnumero) {
        this.prcnumero = prcnumero;
    }
    public String getPrcnombre() {
        return this.prcnombre;
    }
    
    public void setPrcnombre(String prcnombre) {
        this.prcnombre = prcnombre;
    }
    public Float getPrcvalorPorcentaje() {
        return this.prcvalorPorcentaje;
    }
    
    public void setPrcvalorPorcentaje(Float prcvalorPorcentaje) {
        this.prcvalorPorcentaje = prcvalorPorcentaje;
    }
    public Integer getPrchoras() {
        return this.prchoras;
    }
    
    public void setPrchoras(Integer prchoras) {
        this.prchoras = prchoras;
    }




}


