package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0



/**
 * Practicalaboratorio generated by hbm2java
 */
public class Practicalaboratorio  implements java.io.Serializable {


     private Integer prlid;
     private Unidadaprendizaje unidadaprendizaje;
     private int prlnumero;
     private String prlnombre;
     private float prlvalorPorcentaje;
     private Float prlhoras;

    public Practicalaboratorio() {
    }

	
    public Practicalaboratorio(Unidadaprendizaje unidadaprendizaje, int prlnumero, String prlnombre, float prlvalorPorcentaje) {
        this.unidadaprendizaje = unidadaprendizaje;
        this.prlnumero = prlnumero;
        this.prlnombre = prlnombre;
        this.prlvalorPorcentaje = prlvalorPorcentaje;
    }
    public Practicalaboratorio(Unidadaprendizaje unidadaprendizaje, int prlnumero, String prlnombre, float prlvalorPorcentaje, Float prlhoras) {
       this.unidadaprendizaje = unidadaprendizaje;
       this.prlnumero = prlnumero;
       this.prlnombre = prlnombre;
       this.prlvalorPorcentaje = prlvalorPorcentaje;
       this.prlhoras = prlhoras;
    }
   
    public Integer getPrlid() {
        return this.prlid;
    }
    
    public void setPrlid(Integer prlid) {
        this.prlid = prlid;
    }
    public Unidadaprendizaje getUnidadaprendizaje() {
        return this.unidadaprendizaje;
    }
    
    public void setUnidadaprendizaje(Unidadaprendizaje unidadaprendizaje) {
        this.unidadaprendizaje = unidadaprendizaje;
    }
    public int getPrlnumero() {
        return this.prlnumero;
    }
    
    public void setPrlnumero(int prlnumero) {
        this.prlnumero = prlnumero;
    }
    public String getPrlnombre() {
        return this.prlnombre;
    }
    
    public void setPrlnombre(String prlnombre) {
        this.prlnombre = prlnombre;
    }
    public float getPrlvalorPorcentaje() {
        return this.prlvalorPorcentaje;
    }
    
    public void setPrlvalorPorcentaje(float prlvalorPorcentaje) {
        this.prlvalorPorcentaje = prlvalorPorcentaje;
    }
    public Float getPrlhoras() {
        return this.prlhoras;
    }
    
    public void setPrlhoras(Float prlhoras) {
        this.prlhoras = prlhoras;
    }




}


