package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer proid;
     private Usuario usuario;
     private int pronumeroEmpleado;
     private String pronombre;
     private String proapellidoPaterno;
     private String proapellidoMaterno;
     private String prorfc;
     private Set coordinadorareaadministrativas = new HashSet(0);
     private Set programaeducativos = new HashSet(0);
     private Set areaconocimientos = new HashSet(0);
     private Set programaeducativos_1 = new HashSet(0);
     private Set unidadaprendizajeImparteProfesors = new HashSet(0);
     private Set unidadacademicas = new HashSet(0);

    public Profesor() {
    }

	
    public Profesor(Usuario usuario, int pronumeroEmpleado, String pronombre, String proapellidoPaterno, String proapellidoMaterno, String prorfc) {
        this.usuario = usuario;
        this.pronumeroEmpleado = pronumeroEmpleado;
        this.pronombre = pronombre;
        this.proapellidoPaterno = proapellidoPaterno;
        this.proapellidoMaterno = proapellidoMaterno;
        this.prorfc = prorfc;
    }
    public Profesor(Usuario usuario, int pronumeroEmpleado, String pronombre, String proapellidoPaterno, String proapellidoMaterno, String prorfc, Set coordinadorareaadministrativas, Set programaeducativos, Set areaconocimientos, Set programaeducativos_1, Set unidadaprendizajeImparteProfesors, Set unidadacademicas) {
       this.usuario = usuario;
       this.pronumeroEmpleado = pronumeroEmpleado;
       this.pronombre = pronombre;
       this.proapellidoPaterno = proapellidoPaterno;
       this.proapellidoMaterno = proapellidoMaterno;
       this.prorfc = prorfc;
       this.coordinadorareaadministrativas = coordinadorareaadministrativas;
       this.programaeducativos = programaeducativos;
       this.areaconocimientos = areaconocimientos;
       this.programaeducativos_1 = programaeducativos_1;
       this.unidadaprendizajeImparteProfesors = unidadaprendizajeImparteProfesors;
       this.unidadacademicas = unidadacademicas;
    }
   
    public Integer getProid() {
        return this.proid;
    }
    
    public void setProid(Integer proid) {
        this.proid = proid;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getPronumeroEmpleado() {
        return this.pronumeroEmpleado;
    }
    
    public void setPronumeroEmpleado(int pronumeroEmpleado) {
        this.pronumeroEmpleado = pronumeroEmpleado;
    }
    public String getPronombre() {
        return this.pronombre;
    }
    
    public void setPronombre(String pronombre) {
        this.pronombre = pronombre;
    }
    public String getProapellidoPaterno() {
        return this.proapellidoPaterno;
    }
    
    public void setProapellidoPaterno(String proapellidoPaterno) {
        this.proapellidoPaterno = proapellidoPaterno;
    }
    public String getProapellidoMaterno() {
        return this.proapellidoMaterno;
    }
    
    public void setProapellidoMaterno(String proapellidoMaterno) {
        this.proapellidoMaterno = proapellidoMaterno;
    }
    public String getProrfc() {
        return this.prorfc;
    }
    
    public void setProrfc(String prorfc) {
        this.prorfc = prorfc;
    }
    public Set getCoordinadorareaadministrativas() {
        return this.coordinadorareaadministrativas;
    }
    
    public void setCoordinadorareaadministrativas(Set coordinadorareaadministrativas) {
        this.coordinadorareaadministrativas = coordinadorareaadministrativas;
    }
    public Set getProgramaeducativos() {
        return this.programaeducativos;
    }
    
    public void setProgramaeducativos(Set programaeducativos) {
        this.programaeducativos = programaeducativos;
    }
    public Set getAreaconocimientos() {
        return this.areaconocimientos;
    }
    
    public void setAreaconocimientos(Set areaconocimientos) {
        this.areaconocimientos = areaconocimientos;
    }
    public Set getProgramaeducativos_1() {
        return this.programaeducativos_1;
    }
    
    public void setProgramaeducativos_1(Set programaeducativos_1) {
        this.programaeducativos_1 = programaeducativos_1;
    }
    public Set getUnidadaprendizajeImparteProfesors() {
        return this.unidadaprendizajeImparteProfesors;
    }
    
    public void setUnidadaprendizajeImparteProfesors(Set unidadaprendizajeImparteProfesors) {
        this.unidadaprendizajeImparteProfesors = unidadaprendizajeImparteProfesors;
    }
    public Set getUnidadacademicas() {
        return this.unidadacademicas;
    }
    
    public void setUnidadacademicas(Set unidadacademicas) {
        this.unidadacademicas = unidadacademicas;
    }




}


