package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Programaeducativo generated by hbm2java
 */
public class Programaeducativo  implements java.io.Serializable {


     private Integer pedid;
     private Unidadacademica unidadacademica;
     private int pedclave;
     private String pednombre;
     private Set profesors = new HashSet(0);
     private Set areaadministrativas = new HashSet(0);
     private Set planestudios = new HashSet(0);
     private Set profesors_1 = new HashSet(0);

    public Programaeducativo() {
    }

	
    public Programaeducativo(int pedclave, String pednombre) {
        this.pedclave = pedclave;
        this.pednombre = pednombre;
    }
    public Programaeducativo(Unidadacademica unidadacademica, int pedclave, String pednombre, Set profesors, Set areaadministrativas, Set planestudios, Set profesors_1) {
       this.unidadacademica = unidadacademica;
       this.pedclave = pedclave;
       this.pednombre = pednombre;
       this.profesors = profesors;
       this.areaadministrativas = areaadministrativas;
       this.planestudios = planestudios;
       this.profesors_1 = profesors_1;
    }
   
    public Integer getPedid() {
        return this.pedid;
    }
    
    public void setPedid(Integer pedid) {
        this.pedid = pedid;
    }
    public Unidadacademica getUnidadacademica() {
        return this.unidadacademica;
    }
    
    public void setUnidadacademica(Unidadacademica unidadacademica) {
        this.unidadacademica = unidadacademica;
    }
    public int getPedclave() {
        return this.pedclave;
    }
    
    public void setPedclave(int pedclave) {
        this.pedclave = pedclave;
    }
    public String getPednombre() {
        return this.pednombre;
    }
    
    public void setPednombre(String pednombre) {
        this.pednombre = pednombre;
    }
    public Set getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set profesors) {
        this.profesors = profesors;
    }
    public Set getAreaadministrativas() {
        return this.areaadministrativas;
    }
    
    public void setAreaadministrativas(Set areaadministrativas) {
        this.areaadministrativas = areaadministrativas;
    }
    public Set getPlanestudios() {
        return this.planestudios;
    }
    
    public void setPlanestudios(Set planestudios) {
        this.planestudios = planestudios;
    }
    public Set getProfesors_1() {
        return this.profesors_1;
    }
    
    public void setProfesors_1(Set profesors_1) {
        this.profesors_1 = profesors_1;
    }




}


