package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0



/**
 * Reporte generated by hbm2java
 */
public class Reporte  implements java.io.Serializable {


     private ReporteId id;
     private Reporteavancecontenidotematico reporteavancecontenidotematico;
     private String repobservacion;
     private Boolean impartido;

    public Reporte() {
    }

	
    public Reporte(ReporteId id, Reporteavancecontenidotematico reporteavancecontenidotematico, String repobservacion) {
        this.id = id;
        this.reporteavancecontenidotematico = reporteavancecontenidotematico;
        this.repobservacion = repobservacion;
    }
    public Reporte(ReporteId id, Reporteavancecontenidotematico reporteavancecontenidotematico, String repobservacion, Boolean impartido) {
       this.id = id;
       this.reporteavancecontenidotematico = reporteavancecontenidotematico;
       this.repobservacion = repobservacion;
       this.impartido = impartido;
    }
   
    public ReporteId getId() {
        return this.id;
    }
    
    public void setId(ReporteId id) {
        this.id = id;
    }
    public Reporteavancecontenidotematico getReporteavancecontenidotematico() {
        return this.reporteavancecontenidotematico;
    }
    
    public void setReporteavancecontenidotematico(Reporteavancecontenidotematico reporteavancecontenidotematico) {
        this.reporteavancecontenidotematico = reporteavancecontenidotematico;
    }
    public String getRepobservacion() {
        return this.repobservacion;
    }
    
    public void setRepobservacion(String repobservacion) {
        this.repobservacion = repobservacion;
    }
    public Boolean getImpartido() {
        return this.impartido;
    }
    
    public void setImpartido(Boolean impartido) {
        this.impartido = impartido;
    }




}


