package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reporteavancecontenidotematico generated by hbm2java
 */
public class Reporteavancecontenidotematico  implements java.io.Serializable {


     private Integer racid;
     private UnidadaprendizajeImparteProfesor unidadaprendizajeImparteProfesor;
     private String racnumero;
     private Date racfechaElaboracion;
     private float racavanceGlobal;
     private String racstatus;
     private Set reportes = new HashSet(0);

    public Reporteavancecontenidotematico() {
    }

	
    public Reporteavancecontenidotematico(UnidadaprendizajeImparteProfesor unidadaprendizajeImparteProfesor, String racnumero, Date racfechaElaboracion, float racavanceGlobal, String racstatus) {
        this.unidadaprendizajeImparteProfesor = unidadaprendizajeImparteProfesor;
        this.racnumero = racnumero;
        this.racfechaElaboracion = racfechaElaboracion;
        this.racavanceGlobal = racavanceGlobal;
        this.racstatus = racstatus;
    }
    public Reporteavancecontenidotematico(UnidadaprendizajeImparteProfesor unidadaprendizajeImparteProfesor, String racnumero, Date racfechaElaboracion, float racavanceGlobal, String racstatus, Set reportes) {
       this.unidadaprendizajeImparteProfesor = unidadaprendizajeImparteProfesor;
       this.racnumero = racnumero;
       this.racfechaElaboracion = racfechaElaboracion;
       this.racavanceGlobal = racavanceGlobal;
       this.racstatus = racstatus;
       this.reportes = reportes;
    }
   
    public Integer getRacid() {
        return this.racid;
    }
    
    public void setRacid(Integer racid) {
        this.racid = racid;
    }
    public UnidadaprendizajeImparteProfesor getUnidadaprendizajeImparteProfesor() {
        return this.unidadaprendizajeImparteProfesor;
    }
    
    public void setUnidadaprendizajeImparteProfesor(UnidadaprendizajeImparteProfesor unidadaprendizajeImparteProfesor) {
        this.unidadaprendizajeImparteProfesor = unidadaprendizajeImparteProfesor;
    }
    public String getRacnumero() {
        return this.racnumero;
    }
    
    public void setRacnumero(String racnumero) {
        this.racnumero = racnumero;
    }
    public Date getRacfechaElaboracion() {
        return this.racfechaElaboracion;
    }
    
    public void setRacfechaElaboracion(Date racfechaElaboracion) {
        this.racfechaElaboracion = racfechaElaboracion;
    }
    public float getRacavanceGlobal() {
        return this.racavanceGlobal;
    }
    
    public void setRacavanceGlobal(float racavanceGlobal) {
        this.racavanceGlobal = racavanceGlobal;
    }
    public String getRacstatus() {
        return this.racstatus;
    }
    
    public void setRacstatus(String racstatus) {
        this.racstatus = racstatus;
    }
    public Set getReportes() {
        return this.reportes;
    }
    
    public void setReportes(Set reportes) {
        this.reportes = reportes;
    }




}


