package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0



/**
 * ReporteId generated by hbm2java
 */
public class ReporteId  implements java.io.Serializable {


     private int repid;
     private int uniid;
     private int tunid;
     private int sutid;
     private int prlid;
     private int prtid;
     private int prcid;

    public ReporteId() {
    }

    public ReporteId(int repid, int uniid, int tunid, int sutid, int prlid, int prtid, int prcid) {
       this.repid = repid;
       this.uniid = uniid;
       this.tunid = tunid;
       this.sutid = sutid;
       this.prlid = prlid;
       this.prtid = prtid;
       this.prcid = prcid;
    }
   
    public int getRepid() {
        return this.repid;
    }
    
    public void setRepid(int repid) {
        this.repid = repid;
    }
    public int getUniid() {
        return this.uniid;
    }
    
    public void setUniid(int uniid) {
        this.uniid = uniid;
    }
    public int getTunid() {
        return this.tunid;
    }
    
    public void setTunid(int tunid) {
        this.tunid = tunid;
    }
    public int getSutid() {
        return this.sutid;
    }
    
    public void setSutid(int sutid) {
        this.sutid = sutid;
    }
    public int getPrlid() {
        return this.prlid;
    }
    
    public void setPrlid(int prlid) {
        this.prlid = prlid;
    }
    public int getPrtid() {
        return this.prtid;
    }
    
    public void setPrtid(int prtid) {
        this.prtid = prtid;
    }
    public int getPrcid() {
        return this.prcid;
    }
    
    public void setPrcid(int prcid) {
        this.prcid = prcid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReporteId) ) return false;
		 ReporteId castOther = ( ReporteId ) other; 
         
		 return (this.getRepid()==castOther.getRepid())
 && (this.getUniid()==castOther.getUniid())
 && (this.getTunid()==castOther.getTunid())
 && (this.getSutid()==castOther.getSutid())
 && (this.getPrlid()==castOther.getPrlid())
 && (this.getPrtid()==castOther.getPrtid())
 && (this.getPrcid()==castOther.getPrcid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRepid();
         result = 37 * result + this.getUniid();
         result = 37 * result + this.getTunid();
         result = 37 * result + this.getSutid();
         result = 37 * result + this.getPrlid();
         result = 37 * result + this.getPrtid();
         result = 37 * result + this.getPrcid();
         return result;
   }   


}


