package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer rolid;
     private String roltipo;
     private Integer rolprioridad;
     private Set rolHasPermisos = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String roltipo) {
        this.roltipo = roltipo;
    }
    public Rol(String roltipo, Integer rolprioridad, Set rolHasPermisos, Set usuarios) {
       this.roltipo = roltipo;
       this.rolprioridad = rolprioridad;
       this.rolHasPermisos = rolHasPermisos;
       this.usuarios = usuarios;
    }
   
    public Integer getRolid() {
        return this.rolid;
    }
    
    public void setRolid(Integer rolid) {
        this.rolid = rolid;
    }
    public String getRoltipo() {
        return this.roltipo;
    }
    
    public void setRoltipo(String roltipo) {
        this.roltipo = roltipo;
    }
    public Integer getRolprioridad() {
        return this.rolprioridad;
    }
    
    public void setRolprioridad(Integer rolprioridad) {
        this.rolprioridad = rolprioridad;
    }
    public Set getRolHasPermisos() {
        return this.rolHasPermisos;
    }
    
    public void setRolHasPermisos(Set rolHasPermisos) {
        this.rolHasPermisos = rolHasPermisos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


