package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0



/**
 * RolHasPermiso generated by hbm2java
 */
public class RolHasPermiso  implements java.io.Serializable {


     private RolHasPermisoId id;
     private Subpermisos subpermisos;
     private Permiso permiso;
     private Rol rol;

    public RolHasPermiso() {
    }

    public RolHasPermiso(RolHasPermisoId id, Subpermisos subpermisos, Permiso permiso, Rol rol) {
       this.id = id;
       this.subpermisos = subpermisos;
       this.permiso = permiso;
       this.rol = rol;
    }
   
    public RolHasPermisoId getId() {
        return this.id;
    }
    
    public void setId(RolHasPermisoId id) {
        this.id = id;
    }
    public Subpermisos getSubpermisos() {
        return this.subpermisos;
    }
    
    public void setSubpermisos(Subpermisos subpermisos) {
        this.subpermisos = subpermisos;
    }
    public Permiso getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(Permiso permiso) {
        this.permiso = permiso;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


