package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0



/**
 * RolHasPermisoId generated by hbm2java
 */
public class RolHasPermisoId  implements java.io.Serializable {


     private int rolRolid;
     private int permisoPerid;
     private int subpermisosSperid;

    public RolHasPermisoId() {
    }

    public RolHasPermisoId(int rolRolid, int permisoPerid, int subpermisosSperid) {
       this.rolRolid = rolRolid;
       this.permisoPerid = permisoPerid;
       this.subpermisosSperid = subpermisosSperid;
    }
   
    public int getRolRolid() {
        return this.rolRolid;
    }
    
    public void setRolRolid(int rolRolid) {
        this.rolRolid = rolRolid;
    }
    public int getPermisoPerid() {
        return this.permisoPerid;
    }
    
    public void setPermisoPerid(int permisoPerid) {
        this.permisoPerid = permisoPerid;
    }
    public int getSubpermisosSperid() {
        return this.subpermisosSperid;
    }
    
    public void setSubpermisosSperid(int subpermisosSperid) {
        this.subpermisosSperid = subpermisosSperid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolHasPermisoId) ) return false;
		 RolHasPermisoId castOther = ( RolHasPermisoId ) other; 
         
		 return (this.getRolRolid()==castOther.getRolRolid())
 && (this.getPermisoPerid()==castOther.getPermisoPerid())
 && (this.getSubpermisosSperid()==castOther.getSubpermisosSperid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRolRolid();
         result = 37 * result + this.getPermisoPerid();
         result = 37 * result + this.getSubpermisosSperid();
         return result;
   }   


}


