package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Subpermisos generated by hbm2java
 */
public class Subpermisos  implements java.io.Serializable {


     private Integer sperid;
     private String spertipo;
     private int spervalor;
     private Set rolHasPermisos = new HashSet(0);

    public Subpermisos() {
    }

	
    public Subpermisos(String spertipo, int spervalor) {
        this.spertipo = spertipo;
        this.spervalor = spervalor;
    }
    public Subpermisos(String spertipo, int spervalor, Set rolHasPermisos) {
       this.spertipo = spertipo;
       this.spervalor = spervalor;
       this.rolHasPermisos = rolHasPermisos;
    }
   
    public Integer getSperid() {
        return this.sperid;
    }
    
    public void setSperid(Integer sperid) {
        this.sperid = sperid;
    }
    public String getSpertipo() {
        return this.spertipo;
    }
    
    public void setSpertipo(String spertipo) {
        this.spertipo = spertipo;
    }
    public int getSpervalor() {
        return this.spervalor;
    }
    
    public void setSpervalor(int spervalor) {
        this.spervalor = spervalor;
    }
    public Set getRolHasPermisos() {
        return this.rolHasPermisos;
    }
    
    public void setRolHasPermisos(Set rolHasPermisos) {
        this.rolHasPermisos = rolHasPermisos;
    }




}


