package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Temaunidad generated by hbm2java
 */
public class Temaunidad  implements java.io.Serializable {


     private Integer tunid;
     private Unidad unidad;
     private String tunnumero;
     private String tunnombre;
     private float tunvalorPorcentaje;
     private Float tunhoras;
     private Boolean tunhorasCompletas;
     private Set subtemaunidads = new HashSet(0);

    public Temaunidad() {
    }

	
    public Temaunidad(Unidad unidad, String tunnumero, String tunnombre, float tunvalorPorcentaje) {
        this.unidad = unidad;
        this.tunnumero = tunnumero;
        this.tunnombre = tunnombre;
        this.tunvalorPorcentaje = tunvalorPorcentaje;
    }
    public Temaunidad(Unidad unidad, String tunnumero, String tunnombre, float tunvalorPorcentaje, Float tunhoras, Boolean tunhorasCompletas, Set subtemaunidads) {
       this.unidad = unidad;
       this.tunnumero = tunnumero;
       this.tunnombre = tunnombre;
       this.tunvalorPorcentaje = tunvalorPorcentaje;
       this.tunhoras = tunhoras;
       this.tunhorasCompletas = tunhorasCompletas;
       this.subtemaunidads = subtemaunidads;
    }
   
    public Integer getTunid() {
        return this.tunid;
    }
    
    public void setTunid(Integer tunid) {
        this.tunid = tunid;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public String getTunnumero() {
        return this.tunnumero;
    }
    
    public void setTunnumero(String tunnumero) {
        this.tunnumero = tunnumero;
    }
    public String getTunnombre() {
        return this.tunnombre;
    }
    
    public void setTunnombre(String tunnombre) {
        this.tunnombre = tunnombre;
    }
    public float getTunvalorPorcentaje() {
        return this.tunvalorPorcentaje;
    }
    
    public void setTunvalorPorcentaje(float tunvalorPorcentaje) {
        this.tunvalorPorcentaje = tunvalorPorcentaje;
    }
    public Float getTunhoras() {
        return this.tunhoras;
    }
    
    public void setTunhoras(Float tunhoras) {
        this.tunhoras = tunhoras;
    }
    public Boolean getTunhorasCompletas() {
        return this.tunhorasCompletas;
    }
    
    public void setTunhorasCompletas(Boolean tunhorasCompletas) {
        this.tunhorasCompletas = tunhorasCompletas;
    }
    public Set getSubtemaunidads() {
        return this.subtemaunidads;
    }
    
    public void setSubtemaunidads(Set subtemaunidads) {
        this.subtemaunidads = subtemaunidads;
    }




}


