package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Unidad generated by hbm2java
 */
public class Unidad  implements java.io.Serializable {


     private Integer uniid;
     private Unidadaprendizaje unidadaprendizaje;
     private Integer uninumero;
     private String uninombre;
     private float univalorPorcentaje;
     private float unihoras;
     private Boolean unihorasCompletas;
     private Set temaunidads = new HashSet(0);

    public Unidad() {
    }

	
    public Unidad(Unidadaprendizaje unidadaprendizaje, float univalorPorcentaje, float unihoras) {
        this.unidadaprendizaje = unidadaprendizaje;
        this.univalorPorcentaje = univalorPorcentaje;
        this.unihoras = unihoras;
    }
    public Unidad(Unidadaprendizaje unidadaprendizaje, Integer uninumero, String uninombre, float univalorPorcentaje, float unihoras, Boolean unihorasCompletas, Set temaunidads) {
       this.unidadaprendizaje = unidadaprendizaje;
       this.uninumero = uninumero;
       this.uninombre = uninombre;
       this.univalorPorcentaje = univalorPorcentaje;
       this.unihoras = unihoras;
       this.unihorasCompletas = unihorasCompletas;
       this.temaunidads = temaunidads;
    }
   
    public Integer getUniid() {
        return this.uniid;
    }
    
    public void setUniid(Integer uniid) {
        this.uniid = uniid;
    }
    public Unidadaprendizaje getUnidadaprendizaje() {
        return this.unidadaprendizaje;
    }
    
    public void setUnidadaprendizaje(Unidadaprendizaje unidadaprendizaje) {
        this.unidadaprendizaje = unidadaprendizaje;
    }
    public Integer getUninumero() {
        return this.uninumero;
    }
    
    public void setUninumero(Integer uninumero) {
        this.uninumero = uninumero;
    }
    public String getUninombre() {
        return this.uninombre;
    }
    
    public void setUninombre(String uninombre) {
        this.uninombre = uninombre;
    }
    public float getUnivalorPorcentaje() {
        return this.univalorPorcentaje;
    }
    
    public void setUnivalorPorcentaje(float univalorPorcentaje) {
        this.univalorPorcentaje = univalorPorcentaje;
    }
    public float getUnihoras() {
        return this.unihoras;
    }
    
    public void setUnihoras(float unihoras) {
        this.unihoras = unihoras;
    }
    public Boolean getUnihorasCompletas() {
        return this.unihorasCompletas;
    }
    
    public void setUnihorasCompletas(Boolean unihorasCompletas) {
        this.unihorasCompletas = unihorasCompletas;
    }
    public Set getTemaunidads() {
        return this.temaunidads;
    }
    
    public void setTemaunidads(Set temaunidads) {
        this.temaunidads = temaunidads;
    }




}


