package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Unidadacademica generated by hbm2java
 */
public class Unidadacademica  implements java.io.Serializable {


     private Integer uacid;
     private Campus campus;
     private int uacclave;
     private String uacnombre;
     private String uactipo;
     private Set programaeducativos = new HashSet(0);
     private Set profesors = new HashSet(0);

    public Unidadacademica() {
    }

	
    public Unidadacademica(int uacclave, String uacnombre) {
        this.uacclave = uacclave;
        this.uacnombre = uacnombre;
    }
    public Unidadacademica(Campus campus, int uacclave, String uacnombre, String uactipo, Set programaeducativos, Set profesors) {
       this.campus = campus;
       this.uacclave = uacclave;
       this.uacnombre = uacnombre;
       this.uactipo = uactipo;
       this.programaeducativos = programaeducativos;
       this.profesors = profesors;
    }
   
    public Integer getUacid() {
        return this.uacid;
    }
    
    public void setUacid(Integer uacid) {
        this.uacid = uacid;
    }
    public Campus getCampus() {
        return this.campus;
    }
    
    public void setCampus(Campus campus) {
        this.campus = campus;
    }
    public int getUacclave() {
        return this.uacclave;
    }
    
    public void setUacclave(int uacclave) {
        this.uacclave = uacclave;
    }
    public String getUacnombre() {
        return this.uacnombre;
    }
    
    public void setUacnombre(String uacnombre) {
        this.uacnombre = uacnombre;
    }
    public String getUactipo() {
        return this.uactipo;
    }
    
    public void setUactipo(String uactipo) {
        this.uactipo = uactipo;
    }
    public Set getProgramaeducativos() {
        return this.programaeducativos;
    }
    
    public void setProgramaeducativos(Set programaeducativos) {
        this.programaeducativos = programaeducativos;
    }
    public Set getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set profesors) {
        this.profesors = profesors;
    }




}


