package mx.avanti.siract.business.entity;
// Generated 17-ago-2015 14:50:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadaprendizajeImparteProfesor generated by hbm2java
 */
public class UnidadaprendizajeImparteProfesor  implements java.io.Serializable {


     private Integer uipid;
     private Unidadaprendizaje unidadaprendizaje;
     private Profesor profesor;
     private Grupo grupo;
     private String uiptipoSubgrupo;
     private String uipsubgrupo;
     private Set reporteavancecontenidotematicos = new HashSet(0);

    public UnidadaprendizajeImparteProfesor() {
    }

	
    public UnidadaprendizajeImparteProfesor(Unidadaprendizaje unidadaprendizaje, Profesor profesor, Grupo grupo) {
        this.unidadaprendizaje = unidadaprendizaje;
        this.profesor = profesor;
        this.grupo = grupo;
    }
    public UnidadaprendizajeImparteProfesor(Unidadaprendizaje unidadaprendizaje, Profesor profesor, Grupo grupo, String uiptipoSubgrupo, String uipsubgrupo, Set reporteavancecontenidotematicos) {
       this.unidadaprendizaje = unidadaprendizaje;
       this.profesor = profesor;
       this.grupo = grupo;
       this.uiptipoSubgrupo = uiptipoSubgrupo;
       this.uipsubgrupo = uipsubgrupo;
       this.reporteavancecontenidotematicos = reporteavancecontenidotematicos;
    }
   
    public Integer getUipid() {
        return this.uipid;
    }
    
    public void setUipid(Integer uipid) {
        this.uipid = uipid;
    }
    public Unidadaprendizaje getUnidadaprendizaje() {
        return this.unidadaprendizaje;
    }
    
    public void setUnidadaprendizaje(Unidadaprendizaje unidadaprendizaje) {
        this.unidadaprendizaje = unidadaprendizaje;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public String getUiptipoSubgrupo() {
        return this.uiptipoSubgrupo;
    }
    
    public void setUiptipoSubgrupo(String uiptipoSubgrupo) {
        this.uiptipoSubgrupo = uiptipoSubgrupo;
    }
    public String getUipsubgrupo() {
        return this.uipsubgrupo;
    }
    
    public void setUipsubgrupo(String uipsubgrupo) {
        this.uipsubgrupo = uipsubgrupo;
    }
    public Set getReporteavancecontenidotematicos() {
        return this.reporteavancecontenidotematicos;
    }
    
    public void setReporteavancecontenidotematicos(Set reporteavancecontenidotematicos) {
        this.reporteavancecontenidotematicos = reporteavancecontenidotematicos;
    }




}


